import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import AdminLayout from "../../components/admin/AdminLayout";
import { listAdminApplications, listAdminInternships } from "../../services/careerService";
import { listAdminReviewReports } from "../../services/contentService";
import { applicationStatusLabels, type AdminApplication, type Internship } from "../../types/career";
import type { ReviewReport } from "../../types/content";

export default function AdminDashboard() { const [jobs, setJobs] = useState<Internship[]>([]); const [applications, setApplications] = useState<AdminApplication[]>([]); const [reports, setReports] = useState<ReviewReport[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); useEffect(() => { void Promise.all([listAdminInternships(), listAdminApplications(), listAdminReviewReports()]).then(([nextJobs, nextApplications, nextReports]) => { setJobs(nextJobs); setApplications(nextApplications); setReports(nextReports); }).catch(() => setError("管理データを取得できませんでした。" )).finally(() => setLoading(false)); }, []); const stats = useMemo(() => [{ label: "公開中の求人", value: jobs.filter((item) => item.status === "published").length }, { label: "下書き", value: jobs.filter((item) => item.status === "draft").length }, { label: "応募総数", value: applications.length }, { label: "未確認の応募", value: applications.filter((item) => item.status === "submitted").length }, { label: "面接中", value: applications.filter((item) => item.status === "interview").length }, { label: "未対応の通報", value: reports.filter((item) => item.status === "pending").length }], [applications, jobs, reports]); return <AdminLayout title="ダッシュボード">{loading ? <div className="careerState">集計しています...</div> : error ? <div className="careerState isError">{error}</div> : <><section className="adminStats">{stats.map((stat) => <article key={stat.label}><span>{stat.label}</span><strong>{stat.value}</strong><small>件</small></article>)}</section><div className="adminDashboardGrid"><section className="adminPanel"><div className="adminPanelHeader"><h2>最近の応募</h2><Link to="/admin/applications">すべて見る</Link></div>{applications.slice(0, 5).map((item) => <Link className="adminListRow" to={`/admin/applications/${item.id}`} key={item.id}><div><strong>{item.applicant_name}</strong><span>{item.internship?.title}</span></div><span className={`statusBadge is-${item.status}`}>{applicationStatusLabels[item.status]}</span></Link>)}</section><section className="adminPanel"><div className="adminPanelHeader"><h2>締切が近い求人</h2><Link to="/admin/internships">求人管理</Link></div>{jobs.filter((item) => item.status === "published").sort((a, b) => a.deadline.localeCompare(b.deadline)).slice(0, 5).map((item) => <Link className="adminListRow" to={`/admin/internships/${item.id}/edit`} key={item.id}><div><strong>{item.title}</strong><span>{item.company_name}</span></div><time>{new Intl.DateTimeFormat("ja-JP").format(new Date(item.deadline))}</time></Link>)}</section></div></>}</AdminLayout>; }
